name: CI

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Run a one-line script
      run: echo Hello, world! ${GITHUB_REF#refs/tags/}
    - name: Run a multi-line script
      run: |
        echo Add other actions to build,
        echo test, and deploy your project.
        [ -z ${GITHUB_REF#refs/tags/} ] && echo empty || echo filled
